### ISSUE TITLE
Adding second address gives error. 

### ISSUE THREAD

**Issue by himankbhalla** [coding-blocks/oneauth#121] opened 2018-05-12 10:34 UTC
Handle the primary address flag properly.

**Comment by championswimmer** [comment] 2018-05-12 10:51
Do you have the error stacktrace  ?

**Comment by himankbhalla** [comment] 2018-05-12 11:03
Primary flag is not handled correctly.

**Comment by VibhorCodecianGupta** [comment] 2018-07-02 19:56
Couldn't reproduce this, I think it's resolved. Please close this @championswimmer  @himankbhalla  :)

**Closed** 2018-07-02 21:04 UTC
Labels: BOSS, BOUNTY: 200
