### ISSUE TITLE
Bug:College Name and Branch Name is'nt showing after editing.

### ISSUE THREAD

**Issue by Dhroov7** [coding-blocks/oneauth#134] opened 2018-05-15 19:23 UTC
![screen shot 2018-05-16 at 12 53 15 am](https://user-images.githubusercontent.com/18377905/40078870-739cf182-5875-11e8-9de6-7e8d788b2b9f.png)

**Comment by AdityaHirapara** [comment] 2018-05-17 19:54
@Dhroov7 can you explain how did you get this error, As I am unable to reproduce it.

**Comment by Dhroov7** [comment] 2018-05-18 13:18
@AdityaHirapara When i was editing my profile and adding my college name and branch,i get this error on this page after adding the college name and branch.

**Comment by bhavyaagg** [comment] 2018-05-23 08:53
@championswimmer Fixed in #155

**Closed** 2018-05-23 17:54 UTC
Labels: BOSS, BOUNTY: 200
