### ISSUE TITLE
Facebook login button is not working in app

### ISSUE THREAD

**Issue by joeedwin** [coding-blocks/oneauth#634] opened 2019-06-19 13:38 UTC
**Describe the bug**

Facebook login is not working in app
On pressing FB login button it shows "cannot read property of null"

**To Reproduce**

open app and press Facebook login button

**Expected behavior**

Facebook login should work in mobile app

**Screenshots**

![](https://user-images.githubusercontent.com/26297616/59697115-e9b82b00-920a-11e9-8485-17980502f55e.jpeg)

**Would you like to work on the issue?**
yes

**Comment by nik72619c** [comment] 2019-10-23 16:50
Is it free to work on ?

**Comment by Sujal123456** [comment] 2020-05-14 05:00
Can i work on this issue?

**Comment by championswimmer** [comment] 2020-05-20 19:45
duplicate of https://github.com/coding-blocks/oneauth/issues/980

**Closed by championswimmer** 2020-05-20 19:45 UTC
